version: '3'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432

  redis:
    image: redis:5.0.7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
  
  app:
    build:
        context: ./
        dockerfile: Dockerfile-build
        args: 
            NODE_ENV: production
    ports:
      - 4000:${APP_PORT}
    env_file:
      - ./.env
    environment: 
      - NODE_ENV=production
    command: yarn start
    depends_on:
      - postgres
      - redis