FROM node:12.13.1
WORKDIR /usr/app
COPY . ./
RUN yarn install
RUN yarn build

FROM node:12.13.1-alpine
WORKDIR /usr/app
COPY package.json ./
COPY --from=0 /usr/app/dist dist
COPY --from=0 /usr/app/node_modules node_modules