/* tslint:disable */


/**
 * AUTO-GENERATED FILE @ 2019-12-05 15:18:45 - DO NOT EDIT!
 *
 * This file was automatically generated by schemats v.3.0.3
 * $ schemats generate -c postgres://username:password@localhost/test -C -t knex_migrations -t users -t knex_migrations_lock -s public
 *
 */


export namespace KnexMigrationsFields {
    export type id = number;
    export type name = string | null;
    export type batch = number | null;
    export type migrationTime = Date | null;

}

export interface KnexMigrations {
    id: KnexMigrationsFields.id;
    name: KnexMigrationsFields.name;
    batch: KnexMigrationsFields.batch;
    migrationTime: KnexMigrationsFields.migrationTime;

}

export namespace UsersFields {
    export type id = number;
    export type email = string | null;
    export type passwordHash = string | null;
    export type firstName = string | null;
    export type lastName = string | null;
    export type createdAt = Date | null;
    export type updatedAt = Date | null;

}

export interface Users {
    id: UsersFields.id;
    email: UsersFields.email;
    passwordHash: UsersFields.passwordHash;
    firstName: UsersFields.firstName;
    lastName: UsersFields.lastName;
    createdAt: UsersFields.createdAt;
    updatedAt: UsersFields.updatedAt;

}

export namespace KnexMigrationsLockFields {
    export type index = number;
    export type isLocked = number | null;

}

export interface KnexMigrationsLock {
    index: KnexMigrationsLockFields.index;
    isLocked: KnexMigrationsLockFields.isLocked;

}
